User.create(name: "Admin")

City.create(name: "New York City", country: "United States", continent: "North America", description: "New York City comprises 5 boroughs sitting where the Hudson River meets the Atlantic Ocean. At its core is Manhattan, a densely populated borough that’s among the world’s major commercial, financial and cultural centers. Its iconic sites include skyscrapers such as the Empire State Building and sprawling Central Park. Broadway theater is staged in neon-lit Times Square.", display_url: "https://www.youtube.com/watch?v=iEmfFT1CoqQ")
City.create(name: "Tokyo", country: "Japan", continent: "Asia", description: "Tokyo, Japan’s busy capital, mixes the ultramodern and the traditional, from neon-lit skyscrapers to historic temples. The opulent Meiji Shinto Shrine is known for its towering gate and surrounding woods. The Imperial Palace sits amid large public gardens. The city's many museums offer exhibits ranging from classical art (in the Tokyo National Museum) to a reconstructed kabuki theater (in the Edo-Tokyo Museum).", display_url: "https://www.youtube.com/watch?v=I9aJsKcQOAo")
City.create(name: "Chicago", country: "United States", continent: "North America", description: "Chicago, on Lake Michigan in Illinois, is among the largest cities in the U.S. Famed for its bold architecture, it has a skyline punctuated by skyscrapers such as the iconic John Hancock Center, 1,451-ft. Willis Tower (formerly the Sears Tower) and the neo-Gothic Tribune Tower. The city is also renowned for its museums, including the Art Institute of Chicago with its noted Impressionist and Post-Impressionist works.", display_url: "https://www.youtube.com/watch?v=-4VmtE2O8Lo")
City.create(name: "Los Angeles", country: "United States", continent: "North America", description: "Los Angeles is a sprawling Southern California city and the center of the nation’s film and television industry. Near its iconic Hollywood sign, studios such as Paramount Pictures, Universal and Warner Brothers offer behind-the-scenes tours. On Hollywood Boulevard, TCL Chinese Theatre displays celebrities’ hand- and footprints, the Walk of Fame honors thousands of luminaries and vendors sell maps to stars’ homes.", display_url: "https://www.youtube.com/watch?v=vGGL7X_s4AQ")
City.create(name: "San Francisco", country: "United States", continent: "North America", description: "San Francisco, officially the City and County of San Francisco, is a cultural, commercial, and financial center of Northern California. San Francisco is the 16th most populous city in the United States, and the fourth most populous in California, with 881,549 residents as of 2019.", display_url: "https://www.youtube.com/watch?v=hanE_bysWro")
City.create(name: "Las Vegas", country: "United States", continent: "North America", description: "Las Vegas, officially the City of Las Vegas and often known simply as Vegas, is the 28th-most populous city in the United States, the most populous city in the state of Nevada, and the county seat of Clark County.", display_url: "https://www.youtube.com/watch?v=Inun9TW-0Fo")
City.create(name: "Toronto", country: "Canada", continent: "North America", description: "Toronto, the capital of the province of Ontario, is a major Canadian city along Lake Ontario’s northwestern shore. It's a dynamic metropolis with a core of soaring skyscrapers, all dwarfed by the iconic, free-standing CN Tower. Toronto also has many green spaces, from the orderly oval of Queen’s Park to 400-acre High Park and its trails, sports facilities and zoo.", display_url: "https://www.youtube.com/watch?v=bZvjlI-p5wE")
City.create(name: "Mexico City", country: "Mexico", continent: "North America", description: "Mexico City is the densely populated, high-altitude capital of Mexico. It's known for its Templo Mayor (a 13th-century Aztec temple), the baroque Catedral Metropolitana de México of the Spanish conquistadors and the Palacio Nacional, which houses historic murals by Diego Rivera. All of these are situated in and around the Plaza de la Constitución, the massive main square also known as the Zócalo.", display_url: "https://www.youtube.com/watch?v=QqsyIhIPng0")
City.create(name: "Buenos Aires", country: "Argentina", continent: "South America", description: "Buenos Aires is Argentina’s big, cosmopolitan capital city. Its center is the Plaza de Mayo, lined with stately 19th-century buildings including Casa Rosada, the iconic, balconied presidential palace. Other major attractions include Teatro Colón, a grand 1908 opera house with nearly 2,500 seats, and the modern MALBA museum, displaying Latin American art.", display_url: "https://www.youtube.com/watch?v=wEce_3CLZ6k")
City.create(name: "Amsterdam", country: "Netherlands", continent: "Europe", description: "Amsterdam is the Netherlands’ capital, known for its artistic heritage, elaborate canal system and narrow houses with gabled facades, legacies of the city’s 17th-century Golden Age. Its Museum District houses the Van Gogh Museum, works by Rembrandt and Vermeer at the Rijksmuseum, and modern art at the Stedelijk. Cycling is key to the city’s character, and there are numerous bike paths.", display_url: "https://www.youtube.com/watch?v=Oxv6IRcuNaI")
City.create(name: "London", country: "United Kingdom", continent: "Europe", description: "London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic ‘Big Ben’ clock tower and Westminster Abbey, site of British monarch coronations. Across the Thames River, the London Eye observation wheel provides panoramic views of the South Bank cultural complex, and the entire city.", display_url: "https://www.youtube.com/watch?v=gs-skMbz9vo")
City.create(name: "Barcelona", country: "Spain", continent: "Europe", description: "Barcelona, the cosmopolitan capital of Spain’s Catalonia region, is known for its art and architecture. The fantastical Sagrada Família church and other modernist landmarks designed by Antoni Gaudí dot the city. Museu Picasso and Fundació Joan Miró feature modern art by their namesakes. City history museum MUHBA, includes several Roman archaeological sites.", display_url: "https://www.youtube.com/watch?v=gs-skMbz9vo")
City.create(name: "Paris", country: "France", continent: "Europe", description: "Paris, France's capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine. Beyond such landmarks as the Eiffel Tower and the 12th-century, Gothic Notre-Dame cathedral, the city is known for its cafe culture and designer boutiques along the Rue du Faubourg Saint-Honoré.", display_url: "https://www.youtube.com/watch?v=72kRM86V-dw")
City.create(name: "Milan", country: "Italy", continent: "Europe", description: "Milan, a metropolis in Italy's northern Lombardy region, is a global capital of fashion and design. Home to the national stock exchange, it’s a financial hub also known for its high-end restaurants and shops. The Gothic Duomo di Milano cathedral and the Santa Maria delle Grazie convent, housing Leonardo da Vinci’s mural “The Last Supper,” testify to centuries of art and culture. ", display_url: "https://www.youtube.com/watch?v=fL_-mC7DHs8")
City.create(name: "Berlin", country: "Germany", continent: "Europe", description: "Berlin, Germany’s capital, dates to the 13th century. Reminders of the city's turbulent 20th-century history include its Holocaust memorial and the Berlin Wall's graffitied remains. Divided during the Cold War, its 18th-century Brandenburg Gate has become a symbol of reunification. The city's also known for its art scene and modern landmarks like the gold-colored, swoop-roofed Berliner Philharmonie, built in 1963.", display_url: "https://www.youtube.com/watch?v=alyRqOpiHBk&t=51s")
City.create(name: "Prague", country: "Czech Republic", continent: "Europe", description: "Prague, capital city of the Czech Republic, is bisected by the Vltava River. Nicknamed “the City of a Hundred Spires,” it's known for its Old Town Square, the heart of its historic core, with colorful baroque buildings, Gothic churches and the medieval Astronomical Clock, which gives an animated hourly show. Completed in 1402, pedestrian Charles Bridge is lined with statues of Catholic saints.", display_url: "https://www.youtube.com/watch?v=s33wCUfu81Q")
City.create(name: "Istanbul", country: "Turkey", continent: "Europe", description: "Istanbul is a major city in Turkey that straddles Europe and Asia across the Bosphorus Strait. Its Old City reflects cultural influences of the many empires that once ruled here. In the Sultanahmet district, the open-air, Roman-era Hippodrome was for centuries the site of chariot races, and Egyptian obelisks also remain. The iconic Byzantine Hagia Sophia features a soaring 6th-century dome and rare Christian mosaics.", display_url: "https://www.youtube.com/watch?v=NjqOc8k5kjc")
City.create(name: "Capetown", country: "South Africa", continent: "Africa", description: "Cape Town is a port city on South Africa’s southwest coast, on a peninsula beneath the imposing Table Mountain. Slowly rotating cable cars climb to the mountain’s flat top, from which there are sweeping views of the city, the busy harbor and boats heading for Robben Island, the notorious prison that once held Nelson Mandela, which is now a living museum.", display_url: "https://www.youtube.com/watch?v=NjqOc8k5kjc")
City.create(name: "Sydney", country: "Australia", continent: "Austalia", description: "Sydney, capital of New South Wales and one of Australia's largest cities, is best known for its harbourfront Sydney Opera House, with a distinctive sail-like design. Massive Darling Harbour and the smaller Circular Quay port are hubs of waterside life, with the arched Harbour Bridge and esteemed Royal Botanic Garden nearby. Sydney Tower’s outdoor platform, the Skywalk, offers 360-degree views of the city and suburbs.", display_url: "https://www.youtube.com/watch?v=Yc7r_bbt00M")
City.create(name: "Dubai", country: "United Arab Emirates", continent: "Asia", description: "Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture and a lively nightlife scene. Burj Khalifa, an 830m-tall tower, dominates the skyscraper-filled skyline. At its foot lies Dubai Fountain, with jets and lights choreographed to music. On artificial islands just offshore is Atlantis, The Palm, a resort with water and marine-animal parks.", display_url: "https://www.youtube.com/watch?v=dMHUq6vJv-4")
City.create(name: "Hong Kong", country: "Hong Kong", continent: "Asia", description: "Hong Kong, officially the Hong Kong Special Administrative Region of the People's Republic of China, is a metropolitan area and special administrative region of the People's Republic of China on the eastern Pearl River Delta of the South China Sea.", display_url: "https://www.youtube.com/watch?v=gYO1uk7vIcc")
City.create(name: "Bangkok", country: "Thailand", continent: "Asia", description: "Bangkok, Thailand’s capital, is a large city known for ornate shrines and vibrant street life. The boat-filled Chao Phraya River feeds its network of canals, flowing past the Rattanakosin royal district, home to opulent Grand Palace and its sacred Wat Phra Kaew Temple. Nearby is Wat Pho Temple with an enormous reclining Buddha and, on the opposite shore, Wat Arun Temple with its steep steps and Khmer-style spire.", display_url: "https://www.youtube.com/watch?v=oJKDjCxKgkI")
City.create(name: "Phuket", country: "Thailand", continent: "Asia", description: "Phuket City, on Phuket Island, is the capital of Thailand’s Phuket Province. In the Old Town, Thalang Road is lined with colorful 19th-century shophouses and Sino-Portuguese buildings. Built in 1903 by a wealthy tin merchant, Baan Chinpracha mansion has Italian floor tiles, shuttered windows and antique furniture. Set in a 1930s manor, the Thai Hua Museum has exhibits on Phuket’s culture and history.", display_url: "https://www.youtube.com/watch?v=VAV-lDPfuco")
City.create(name: "Singapore", country: "Singapore", continent: "Asia", description: "Singapore is a cosmopolitan city-state in Southeast Asia that became independent from the British in 1965 and is now one of the world’s leading economic centers in shipping and banking. Combining the skyscrapers and subways of a modern, affluent city with a medley of Chinese, Malay, Arab, and Indian influences alongside a tropical climate, tasty food from hawker centres, copious shopping malls, and vibrant night-life scene, this Garden City makes a great stopover or springboard into the region.", display_url: "https://www.youtube.com/watch?v=J_hzi4BCws4")
City.create(name: "Osaka", country: "Japan", continent: "Asia", description: "Osaka is a large port city and commercial center on the Japanese island of Honshu. It's known for its modern architecture, nightlife and hearty street food. The 16th-century shogunate Osaka Castle, which has undergone several restorations, is its main historical landmark. It's surrounded by a moat and park with plum, peach and cherry-blossom trees. Sumiyoshi-taisha is among Japan’s oldest Shinto shrines.", display_url: "https://www.youtube.com/watch?v=jbNmzf5Z7z4")
City.create(name: "Seoul", country: "South Korea", continent: "Asia", description: "Seoul, the capital of South Korea, is a huge metropolis where modern skyscrapers, high-tech subways and pop culture meet Buddhist temples, palaces and street markets. Notable attractions include futuristic Dongdaemun Design Plaza, a convention hall with curving architecture and a rooftop park; Gyeongbokgung Palace, which once had more than 7,000 rooms; and Jogyesa Temple, site of ancient locust and pine trees.", display_url: "https://www.youtube.com/watch?v=P0-weW_fymA")
City.create(name: "Shanghai", country: "China", continent: "Asia", description: "Shanghai, on China’s central coast, is the country's biggest city and a global financial hub. Its heart is the Bund, a famed waterfront promenade lined with colonial-era buildings. Across the Huangpu River rises the Pudong district’s futuristic skyline, including 632m Shanghai Tower and the Oriental Pearl TV Tower, with distinctive pink spheres. Sprawling Yu Garden has traditional pavilions, towers and ponds.", display_url: "https://www.youtube.com/watch?v=3ZyBa5447jY")
City.create(name: "Taipei", country: "Taiwan", continent: "Asia", description: "Taipei, the capital of Taiwan, is a modern metropolis with Japanese colonial lanes, busy shopping streets and contemporary buildings. The skyline is crowned by the 509m-tall, bamboo-shaped Taipei 101 skyscraper, with upscale shops at the base and a rapid elevator to an observatory near the top. Taipei is also known for its lively street-food scene and many night markets, including expansive Shilin market.", display_url: "https://www.youtube.com/watch?v=NmrYaeCs5Zc")
puts "Cities Seeded 🏙"

puts "Seeding NYC Videos 🗽"
Video.create(city_id: 1, user_id: 1, title: "31 NYC Restaurants You Need To Eat In Your Lifetime", category: "Food", video_url: "https://www.youtube.com/watch?v=YvPqrwGDgnM", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "10 Foods You MUST EAT in New York City!", category: "Food", video_url: "https://www.youtube.com/watch?v=DsCnlY1NQ3o", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "The Best Burger In NYC", category: "Food", video_url: "https://www.youtube.com/watch?v=B8YGMGaOUAM", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "The Best Pizza Slice In NYC", category: "Food", video_url: "https://www.youtube.com/watch?v=9o1jmMaWsr8", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "7 NYC Pizzerias You Must Visit", category: "Food", video_url: "https://www.youtube.com/watch?v=0antNEgkC6E", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Pizza Tour of New York City", category: "Food", video_url: "https://www.youtube.com/watch?v=Hi4sjsOPOQQ", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Where To Eat in Chinatown NYC ? 10 BEST Cheap Food Joints !", category: "Food", video_url: "https://www.youtube.com/watch?v=cI_JbBZNtUI", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "NYC's Best Halal Carts! - New York City Halal Food", category: "Food", video_url: "https://www.youtube.com/watch?v=UawBqLfbNTg", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "11 Best Dessert Places in NYC!", category: "Food", video_url: "https://www.youtube.com/watch?v=zgnXeV9ZVNM", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Where to Eat in NYC's Little Italy - Food Neighborhoods, Episode 1", category: "Food", video_url: "https://www.youtube.com/watch?v=B0iO5CU7IBs", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York's Hidden Secrets", category: "Cultural", video_url: "https://www.youtube.com/watch?v=SB2SmIAVt8U", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Best Art Museum New York: Metropolitan Museum of Art Tour 5th Avenue", category: "Cultural", video_url: "https://www.youtube.com/watch?v=NsgvcVl6SU8", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "NYC BEST USED BOOKSTORES! (Manhattan)", category: "Cultural", video_url: "https://www.youtube.com/watch?v=B_rgmOsV-nU", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "The Bowery Boys Tour of NYC's Historical Lower East Side", category: "Cultural", video_url: "https://www.youtube.com/watch?v=EF_4gC0F6Js", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Best Art Museum New York: Metropolitan Museum of Art Tour 5th Avenue", category: "Cultural", video_url: "https://www.youtube.com/watch?v=NsgvcVl6SU8", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York City video tour of the Museum of Natural History", category: "Cultural", video_url: "https://www.youtube.com/watch?v=T_Ft8GMyiQc", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Visiting The 9/11 Memorial & Museum In New York", category: "Cultural", video_url: "https://www.youtube.com/watch?v=AkJ0K0IBOA4", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York Aquarium Cinematic Walkthrough Tour", category: "Cultural", video_url: "https://www.youtube.com/watch?v=plDZH7jG6og", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York City Walking Tour Part 1 - Midtown Manhattan (4k Ultra HD 60fps)", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=-IpXdtWfneI", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Christmas Day Walking Tour - New York City", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=dW7lU3LWMPI", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "The Evening Streets of New York, USA", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=PEhKhACVfaA", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Walking in the Rain in Manhattan, NYC", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=eZe4Q_58UTU", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "MANHATTAN | NEW YORK CITY - NY , UNITED STATES - A TRAVEL TOUR", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=FjU_x1106pg", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York City Live Walking Tour in Manhattan", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=L7lkT0AaMd4", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Walking NYC (Narrated) : Downtown Brooklyn,", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=ckXBf7b-q4U", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York City Walking Tour by New York Tour1-Part 1:", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=73NLxZwy5zI", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Walking NYC : SoHo & Greenwich Village at Night", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=4WcMFwU6EpE", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York Walk | NYC Walking Tour | New York VLOG", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=gdkzUeqmk80", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Best Late Night Food in Downtown NYC with Jonnyshipes", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=uqao3dOYO7U", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York City Nightlife during COVID-19", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=4Es7Z8iluq4", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Where to Party in New York", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=97BngUftyzA", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York Nightlife - Lower East Side", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=ql0RwcUbRz8", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "NYC's 7 BEST Speakeasy Bars", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=LtW4PEuxXn4", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "10 BEST Rooftop Bars in New York- NYC Nightlife Guide", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=3emoIdcJfjc", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "LIVING IN NEW YORK CITY: WHERE TO PARTY AT?", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=OtAXP3lgHb4", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York Nightlife - East Village", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=nb5O3FJlQMY", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "BEST Rooftop Bar in New York City? 230 Fifth Bar", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=gDSIE20vrrE", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Top 10 Night Clubs in New York", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=EuYPrP2Nk4Y", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Aire Luxury Spa Wine Bath Experience", category: "Leisure", video_url: "https://www.youtube.com/watch?v=GNxkcQ5zEAs", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "13 Free Things To Do in NYC That Are Actually Worth It", category: "Leisure", video_url: "https://www.youtube.com/watch?v=mtiaQitETmk", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "BEST BASKETBALL COURTS IN NYC ft. DIKEMBE MUTOMBO | Fung Bros", category: "Leisure", video_url: "https://www.youtube.com/watch?v=UvYuTNdJ3pE", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York City CitiBike Tour in Manhattan", category: "Leisure", video_url: "https://www.youtube.com/watch?v=tLSMwfbiwps", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Glass blowing in Red Hook", category: "Leisure", video_url: "https://www.youtube.com/watch?v=CifG_I12Bgs", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Coney Island, Brooklyn - NYC's MOST FAMOUS Beach & Boardwalk !", category: "Leisure", video_url: "https://www.youtube.com/watch?v=Hc3ifiSupMo", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "New York's Best Dog Parks", category: "Leisure", video_url: "https://www.youtube.com/watch?v=NmbbU4jcHNY", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Visiting Mendez Boxing Gym in NYC", category: "Leisure", video_url: "https://www.youtube.com/watch?v=4EYxata7Zmc", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "Skyline NYC Drive In Movie Theater", category: "Leisure", video_url: "https://www.youtube.com/watch?v=OK2Y_6cDVic", likes: rand(50..200))
Video.create(city_id: 1, user_id: 1, title: "The Vigilante Group Of New Yorkers Who Hunt Rats At Night", category: "Leisure", video_url: "https://www.youtube.com/watch?v=jL0x5oBFC1w", likes: rand(50..200))

puts "Seeding Tokyo Videos 🏯"
Video.create(city_id: 2, user_id: 1, title: "Top 5 Things to do in Tokyo | japan-guide.com", category: "Cultural", video_url: "https://www.youtube.com/watch?v=Hr_TbL5ejuQ", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Top Things To Do in Tokyo, Japan 2020 4K", category: "Cultural", video_url: "https://www.youtube.com/watch?v=oik48bGBGBw", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "22 Things To Do in Tokyo, Japan (MUST SEE Attractions)", category: "Cultural", video_url: "https://www.youtube.com/watch?v=62MyzIA8Jh8", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Tokyo's Most Popular Temple: Sensō-ji in Asakusa (guide)", category: "Cultural", video_url: "https://www.youtube.com/watch?v=jsnBgmJ0uhs", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Amazing forest in the middle of Tokyo: Meiji Shrine (guide)", category: "Cultural", video_url: "https://www.youtube.com/watch?v=JsjgeQtOWiU", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Top 7 Museums to Visit | Tokyo Travel", category: "Cultural", video_url: "https://www.youtube.com/watch?v=FDrcs_7EDMQ", likes: rand(50..200))

Video.create(city_id: 2, user_id: 1, title: "5 Must-Try Japanese Food Experiences in Tokyo", category: "Food", video_url: "https://www.youtube.com/watch?v=NGxcr_Z8Dmw&t=649s", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "JAPAN Street Food $100 CHALLENGE in Asakusa, Tokyo! The best Japanese Street Food in Tokyo!", category: "Food", video_url: "https://www.youtube.com/watch?v=An6cuIMTgxo", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Brunch at 7-ELEVEN VS LAWSON in Tokyo Japan", category: "Food", video_url: "https://www.youtube.com/watch?v=QuTE12qGmz8", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Japanese Street Food Tour of TSUKIJI Fish Market Tokyo Japan", category: "Food", video_url: "https://www.youtube.com/watch?v=VWoiDixL5kc", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Japanese Street Food - INSANE $500 Sushi In Tokyo + HUGE Street Food Tour of Tokyo, Japan", category: "Food", video_url: "https://www.youtube.com/watch?v=-fFVW3DfTdU", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Japanese Street Food Tour in Tokyo, Japan - AMAZING Street Food + BEST BBQ Wagyu Beef Steak in Tokyo", category: "Food", video_url: "https://www.youtube.com/watch?v=-D3qsFC0E0E", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Japanese Street Food Tsukiji Outer Market", category: "Food", video_url: "https://www.youtube.com/watch?v=uuvEm8I9i9A", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "JAPANESE STREET FOOD - Tokyo Street Food Tour | AUTHENTIC Street Food in Japan + BEST Oden in TOKYO", category: "Food", video_url: "https://www.youtube.com/watch?v=qtUzkdqL42U", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Japanese Food Tour - HIDDEN-GEMS in Tokyo, Japan | Breakfast, Lunch, and Dinner!", category: "Food", video_url: "https://www.youtube.com/watch?v=iszTT9U4OA8", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "BEST Japanese CURRY! Curry Tour in Tokyo Japan!", category: "Food", video_url: "https://www.youtube.com/watch?v=GE4zbAE5prw", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "LIVING on JAPANESE CONVENIENCE STORES in TOKYO for 24 HOURS!", category: "Food", video_url: "https://www.youtube.com/watch?v=5DaJyPVDOBA", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Japanese Street Food Tour DEEP in Tokyo, Japan! TASTY Japanese BBQ + Pork Gyoza and AMAZING Sushi!", category: "Food", video_url: "https://www.youtube.com/watch?v=HHEFjUWHECg", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "JAPANESE STREET FOOD - Tokyo Street Food Tour | CRAZY Street Food in Japan + BEST Nightlife in TOKYO", category: "Food", video_url: "https://www.youtube.com/watch?v=jOJC42jY864", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "The LARGEST CHINATOWN in Asia! STREET FOOD Tour of Yokohama Chinatown", category: "Food", video_url: "https://www.youtube.com/watch?v=dsxtJUHP_nc", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Ultimate TOKYO RAMEN Tour! RAMEN EXPERT Reveals the Best Noodle Spots in Town!", category: "Food", video_url: "https://www.youtube.com/watch?v=gn8JAm8Gq40", likes: rand(50..200))

Video.create(city_id: 2, user_id: 1, title: "25 Things To Do in Tokyo, Japan (Watch This Before You Go)", category: "Leisure", video_url: "https://www.youtube.com/watch?v=lDoLLhswOwY", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Tokyo’s Most Beautiful Capsule Hotel", category: "Leisure", video_url: "https://www.youtube.com/watch?v=6WNlTEk9Yh0", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "🇯🇵 TOKYO Travel tips 🇯🇵 | Watch BEFORE you go!", category: "Leisure", video_url: "https://www.youtube.com/watch?v=bC9m_id_Yds", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Top 10 Things to DO in SHIBUYA Tokyo | WATCH BEFORE YOU GO", category: "Leisure", video_url: "https://www.youtube.com/watch?v=Evj7OLJ8rcc", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "100 Things to do in TOKYO, JAPAN | Japan Travel Guide", category: "Leisure", video_url: "https://www.youtube.com/watch?v=HYSMJ-lM2t0", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Top 10 Things to DO in SHINJUKU Tokyo | WATCH BEFORE YOU GO", category: "Leisure", video_url: "https://www.youtube.com/watch?v=MjnOaSMnbbY", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "101 Things to DO in TOKYO | Japan Guide to Secret Hidden Places", category: "Leisure", video_url: "https://www.youtube.com/watch?v=8m7dnI2nrU8", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "MORI Building DIGITAL ART MUSEUM: teamLab Borderless (Digest Movie)", category: "Leisure", video_url: "https://www.youtube.com/watch?v=UYFWjUj4RPQ", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "ROBOT RESTAURANT in JAPAN - CRAZY!!! ロボットレストラン - HD 4k", category: "Leisure", video_url: "https://www.youtube.com/watch?v=rLFaNX4WkZ0", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "JAPAN HOT SPRING | Onsen in TOKYO | Ft. Sunnydahye", category: "Leisure", video_url: "https://www.youtube.com/watch?v=93aGXCiY5MQ", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Tour Around Tokyo to Must-Visit Places & Hidden Gems", category: "Leisure", video_url: "https://www.youtube.com/watch?v=LQ5C6MqykZs", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "MARIO KART IN REAL LIFE! (Streets of Tokyo!)", category: "Leisure", video_url: "https://www.youtube.com/watch?v=S7vdmd9qbeM", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "6 Things an Anime Fan Should Do in Tokyo", category: "Leisure", video_url: "https://www.youtube.com/watch?v=VMCMIf-cRYI", likes: rand(50..200))

Video.create(city_id: 2, user_id: 1, title: "Ice Diamonds and Classic Cocktails at Bar High Five", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=i1iqVGORUck", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "JAPAN NIGHTLIFE KABUKICHO Tokyo Red Light District 🔍Robot Restaurant, Godzilla & Funny Salaryman", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=wlOjxhjTLRA", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Bizarre Japanese Bar Food and the Secret Nightlife of Tokyo’s Salarymen!", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=hLLkZsyjn-M", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Japanese Nightlife Etiquette | Beginner's Travel Guide", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=l3ifRE7BQiM", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "TOKYO NIGHTLIFE 2018 4K | PARTYING TRAVEL GUIDE", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=HSTLWBCYxrU", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Tokyo Nightlife in Japan: TOP 30 Bars & Clubs", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=Aam6cU8V4Ow", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "TOKYO NIGHTLIFE GUIDE", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=FqjLOcX3KTc", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Top 5 Pickup Bars in Tokyo - Shibuya", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=ZIt6x8jH5jU", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Jazz Clubs in Tokyo: Blue Note Tokyo", category: "Nightlife", video_url: "https://www.youtube.com/watch?v=J6-FLEiBE84", likes: rand(50..200))

Video.create(city_id: 2, user_id: 1, title: "Walking around Shibuya - Tokyo - 渋谷を歩く- 4K Ultra HD", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=BDW9P60NgHs", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Night walk in Shinjuku, Tokyo", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=vHr4qSQ-5XU", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Walking in the Rain Tokyo, Japan (Relaxing Binaural Thunderstorm Sounds for Sleep) 4k ASMR", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=Et7O5-CzJZg", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Night Walk in Tokyo Red Light District - Shinjuku Kabukicho(歌舞伎町散歩) - Japan Walking Tour", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=n3Dru5y3ROc", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Walking in Tokyo Shibuya at night of 2017", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=6qGiXY1SB68", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Nightlife In Tokyo Shinjuku Streets 4K ASMR", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=1YXmdSVhA3M", likes: rand(50..200))
Video.create(city_id: 2, user_id: 1, title: "Walking around Yokohama Chinatown - Long Take【横浜・中華街】", category: "Walking Tour", video_url: "https://www.youtube.com/watch?v=wGs4ocrLdbc", likes: rand(50..200))

puts "Videos Seeded 📹"

25.times do
    User.create(name: Faker::Twitter.unique.screen_name)
end

puts "Users Seeded 💁‍♂️💁‍♀️"


50.times do
    Comment.create(video_id: Video.all.sample, user_id: User.all.sample, comment: Faker::Marketing.buzzwords)
end


50.times do 
    Comment.create(video_id: Video.all.sample, user_id: User.all.sample, comment: Faker::Movies::HitchhikersGuideToTheGalaxy.quote)
end


50.times do 
    Comment.create(video_id: Video.all.sample, user_id: User.all.sample, comment: Faker::JapaneseMedia::StudioGhibli.quote)
end


puts "Comements Seeded 💬"

puts "Seeding Complete ✅"

